### ISSUE TITLE
Skip NPE if view is null

### ISSUE THREAD

**Issue by sytolk** [ligi/AXT#5]
It`s have

```
@BindView(R.id.view_id)
 View someView;
```
1. Start Background thread
2. User close activity

```
// I don`t know if butterknife BindView will set View to null but with AA it`s null 
View someView = null; 
```

After that Background thread return result in UI thread

```
//after user close Activity
AXT.at(someView).setVisibility(.. -> NPE
```

why not check in:

```
 setVisibility(){ if(this.view!=null) {..}
```

**Comment by ligi** [comment]
Thanks for the info - but I think this check should not be there 
why not 

``` java
if (someview!=null) AXT.at(someview).setVisibility(..
```

**Comment by sytolk** [comment]
Why it`s possible to forget to check :) If check is included in AXT and you use this library for all views its not possible to have NPE

**Comment by ligi** [comment]
Yea but it is not the responsibility of this library. What I could add is a @NotNull annotation - it is not retrofitted with this yet - the lib emerged before support-annotations. 
I do not think it is a good style to add the null-check - so I will not do it
